tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: postgres
    init: |
      RUN sudo apt-get update \
      && sudo apt install postgresql-client



vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - mtxr.sqltools-driver-pg



