tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

  - name: postgres
    init: |
      sudo apt-get update \
      && sudo apt-get install -y postgresql-client \
      && sudo apt-get install cloud-utils

  - name: react-js
    init: |
      cd frontend-react-js
      npm i

  - name: build docker and run
    init: |
      cd ..
      docker compose -f "docker-compose.yml" up -d --build

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - mtxr.sqltools-driver-pg

    - mtxr.sqltools

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public

  - name: backend
    port: 4567
    visibility: public

  - name: xray-daemon
    port: 2000
    visibility: public
